常数表

aidifficulty 常数表:

AI_DIFFICULTY_INSANE AI难度 - 令人发疯的

AI_DIFFICULTY_NEWBIE AI难度 - 新手

AI_DIFFICULTY_NORMAL AI难度 - 正常
alliancetype 常数表:

ALLIANCE_HELP_REQUEST 联盟帮助要求

ALLIANCE_HELP_RESPONSE 联盟帮助响应

ALLIANCE_PASSIVE 被动联盟

ALLIANCE_RESCUABLE 联盟可营救

ALLIANCE_SHARED_ADVANCED_CONTROL 联盟共享高级控制

ALLIANCE_SHARED_CONTROL 联盟共享控制

ALLIANCE_SHARED_SPELLS 联盟共享魔法

ALLIANCE_SHARED_VISION 联盟共享视野

ALLIANCE_SHARED_VISION_FORCED 联盟势力共享视野

ALLIANCE_SHARED_XP 联盟共享优先权
blendmode
常数表:

BLEND_MODE_ADDITIVE 合成算法 - 附加混合

BLEND_MODE_BLEND 合成算法 - 普通混合

BLEND_MODE_DONT_CARE 合成算法 -

  BLEND_MODE_KEYALPHA 合成算法 - 关键的alpha混合

BLEND_MODE_MODULATE 合成算法 - 调整混合

BLEND_MODE_MODULATE_2X 合成算法 - 调整2x混合

BLEND_MODE_NONE 合成算法 - 无混合

boolean
常数表:

FALSE 假

TRUE 真

camerafield
常数表:

CAMERA_FIELD_ANGLE_OF_ATTACK 镜头区域 - 攻击角度

CAMERA_FIELD_FARZ 镜头区域 - 远端

CAMERA_FIELD_FIELD_OF_VIEW 镜头区域 - 区域观看

CAMERA_FIELD_ROLL 镜头区域 - 滚动

CAMERA_FIELD_ROTATION 镜头区域 - 旋转

CAMERA_FIELD_TARGET_DISTANCE 镜头区域 - 距离到目标

CAMERA_FIELD_ZOFFSET 镜头区域 - 高度位移

dialogevent
常数表:

EVENT_DIALOG_BUTTON_CLICK 事件 - 对话按钮点击

EVENT_DIALOG_CLICK 事件 - 对话点击

effecttype
常数表:

EFFECT_TYPE_CASTER 特效类型 - 施法者特效

EFFECT_TYPE_EFFECT 特效类型 - 受影响特效

EFFECT_TYPE_SPECIAL 特效类型 - 特殊特效

EFFECT_TYPE_TARGET 特效类型 - 目标特效

fgamestate
常数表:

GAME_STATE_TIME_OF_DAY 游戏状态 - 时间
fogstate
常数表:

FOG_OF_WAR_FOGGED 可见效果 - 战争迷雾

FOG_OF_WAR_MASKED 可见效果 - 黑色迷雾

FOG_OF_WAR_VISIBLE 可见效果 - 可见
gamedifficulty
常数表:

MAP_DIFFICULTY_EASY 地图难度 - 容易

MAP_DIFFICULTY_HARD 地图难度 - 困难

MAP_DIFFICULTY_INSANE 地图难度 - 令人发疯的

MAP_DIFFICULTY_NORMAL 地图难度 - 正常

gameevent
常数表:

EVENT_GAME_BUILD_SUBMENU 游戏事件 - 创建子菜单

EVENT_GAME_END_LEVEL 游戏事件 - 游戏本关结束

EVENT_GAME_ENTER_REGION 游戏事件 - 进入区域

EVENT_GAME_LEAVE_REGION 游戏事件 - 离开区域

EVENT_GAME_LOADED 游戏事件 - 游戏装载完毕

EVENT_GAME_SAVE 游戏事件 - 储存

EVENT_GAME_SHOW_SKILL 游戏事件 - 显示技能

EVENT_GAME_STATE_LIMIT 游戏事件 - 游戏状态限制

EVENT_GAME_TIMER_EXPIRED 游戏事件 - 游戏超时

EVENT_GAME_TOURNAMENT_FINISH_NOW 游戏事件 - 比赛完成

EVENT_GAME_TOURNAMENT_FINISH_SOON 游戏事件 - 比赛即将完成

EVENT_GAME_TRACKABLE_HIT 游戏事件 - 可跟踪打击

EVENT_GAME_TRACKABLE_TRACK 游戏事件 - 可跟踪跟踪

EVENT_GAME_VARIABLE_LIMIT 游戏事件 - 游戏变量限制

EVENT_GAME_VICTORY 游戏事件 - 游戏胜利

gamespeed
常数表:

MAP_SPEED_FAST 地图 - 较快游戏速度

MAP_SPEED_FASTEST 地图 - 最快游戏速度

MAP_SPEED_NORMAL 地图 - 正常游戏速度

MAP_SPEED_SLOW 地图 - 低游戏速度

MAP_SPEED_SLOWEST 地图 - 最低游戏速度

gametype
常数表:

GAME_TYPE_BLIZ 游戏类型 - 官方地图

GAME_TYPE_FFA 游戏类型 - 自由竞赛

GAME_TYPE_FOUR_TEAM_PLAY 游戏类型 - 4队竞赛

GAME_TYPE_MELEE 游戏类型 - 对战

GAME_TYPE_ONE_ON_ONE 游戏类型 - 1 对 1

GAME_TYPE_THREE_TEAM_PLAY 游戏类型 - 3队竞赛

GAME_TYPE_TWO_TEAM_PLAY 游戏类型 - 2队竞赛

GAME_TYPE_USE_MAP_SETTINGS 游戏类型 - 使用地图设置

igamestate
常数表:

GAME_STATE_DISCONNECTED 游戏状态 - 断开

GAME_STATE_DIVINE_INTERVENTION 游戏状态 - 干涉

integer
常数表:

CAMERA_MARGIN_BOTTOM 镜头空白 - 底部

CAMERA_MARGIN_LEFT 镜头空白 - 左边

CAMERA_MARGIN_RIGHT 镜头空白 - 右边

CAMERA_MARGIN_TOP 镜头空白 - 顶部

JASS_MAX_ARRAY_SIZE 数组最大域值

PLAYER_NEUTRAL_AGGRESSIVE 中立敌对玩家

PLAYER_NEUTRAL_PASSIVE 中立被动玩家

itemtype
常数表:

ITEM_TYPE_ANY 物品类型 - 任何种类

ITEM_TYPE_ARTIFACT 物品类型 - 人造物品

ITEM_TYPE_CAMPAIGN 物品类型 - 战役

ITEM_TYPE_CHARGED 物品类型 - 可充

ITEM_TYPE_MISCELLANEOUS 物品类型 - 混杂

ITEM_TYPE_PERMANENT 物品类型 - 永久

ITEM_TYPE_POWERUP 物品类型 - 升级

ITEM_TYPE_PURCHASABLE 物品类型 - 可购买

ITEM_TYPE_TOME 物品类型 - 书

ITEM_TYPE_UNKNOWN 物品类型 - 未定义种类

limitop
常数表:

EQUAL 等于

GREATER_THAN 大于

GREATER_THAN_OR_EQUAL 大于或等于

LESS_THAN 小于

LESS_THAN_OR_EQUAL 小于等于

NOT_EQUAL 不等于

mapcontrol
常数表:

MAP_CONTROL_COMPUTER 地图控制者 - 电脑

MAP_CONTROL_CREEP 地图控制者 - 野生

MAP_CONTROL_NEUTRAL 地图控制者 - 中立

MAP_CONTROL_NONE 地图控制者 - 无

MAP_CONTROL_RESCUABLE 地图控制者 - 营救

MAP_CONTROL_USER 地图控制者 - 用户

mapdensity
常数表:

MAP_DENSITY_HEAVY 地图 - 高密度

MAP_DENSITY_LIGHT 地图 - 小密度

MAP_DENSITY_MEDIUM 地图 - 中等密度

MAP_DENSITY_NONE 地图 - 无密度

mapflag
常数表:

MAP_ALLIANCE_CHANGES_HIDDEN 地图 - 隐藏改变联盟

MAP_CHEATS 地图 - 容许作弊码

MAP_CHEATS_HIDDEN 地图 - 隐藏作弊码

MAP_FIXED_COLORS 地图 - 固定颜色

MAP_FOG_ALWAYS_VISIBLE 地图迷雾 - 总是可见

MAP_FOG_HIDE_TERRAIN 地图迷雾 - 隐藏地形

MAP_FOG_MAP_EXPLORED 地图迷雾 - 地图已探索

MAP_LOCK_ALLIANCE_CHANGES 地图 - 锁定改变联盟

MAP_LOCK_RANDOM_SEED 地图 - 不容许随机游戏速度

MAP_LOCK_RESOURCE_TRADING 地图 - 锁定资源交易

MAP_LOCK_SPEED 地图 - 锁定游戏速度

MAP_OBSERVERS 地图 - 允许有观察者

MAP_OBSERVERS_ON_DEATH 地图 - 默认为观看者

MAP_RANDOM_HERO 地图 - 随机英雄

MAP_RANDOM_RACES 地图 - 随机种族

MAP_RELOADED 地图 - 地图转换

MAP_RESOURCE_TRADING_ALLIES_ONLY 地图 - 容许联盟资源交易

MAP_SHARED_ADVANCED_CONTROL 地图 - 共享高级控制

MAP_USE_HANDICAPS 地图 - 使用障碍

placement
常数表:

MAP_PLACEMENT_FIXED 地图 - 玩家固定放置

MAP_PLACEMENT_RANDOM 地图 - 玩家随机放置

MAP_PLACEMENT_TEAMS_TOGETHER 地图 - 同一联盟玩家放置在一起

MAP_PLACEMENT_USE_MAP_SETTINGS 地图 - 使用地图设置的玩家放置

playercolor
常数表:

PLAYER_COLOR_AQUA 玩家颜色 - 浅绿

PLAYER_COLOR_BLUE 玩家颜色 - 蓝

PLAYER_COLOR_BROWN 玩家颜色 - 棕色

PLAYER_COLOR_CYAN 玩家颜色 - 青

PLAYER_COLOR_GREEN 玩家颜色 - 绿

PLAYER_COLOR_LIGHT_BLUE 玩家颜色 - 亮蓝

PLAYER_COLOR_LIGHT_GRAY 玩家颜色 - 亮灰

PLAYER_COLOR_ORANGE 玩家颜色 - 橙

PLAYER_COLOR_PINK 玩家颜色 - 粉红

PLAYER_COLOR_PURPLE 玩家颜色 - 紫

PLAYER_COLOR_RED 玩家颜色 - 红

PLAYER_COLOR_YELLOW 玩家颜色 - 黄

playerevent
常数表:

EVENT_PLAYER_ALLIANCE_CHANGED 玩家事件 - 盟友设置变化

EVENT_PLAYER_ARROW_DOWN_DOWN 玩家事件 - 按下键

EVENT_PLAYER_ARROW_DOWN_UP 玩家事件 - 释放下键

EVENT_PLAYER_ARROW_LEFT_DOWN 玩家事件 - 按左键

EVENT_PLAYER_ARROW_LEFT_UP 玩家事件 - 释放左键

EVENT_PLAYER_ARROW_RIGHT_DOWN 玩家事件 - 按右键

EVENT_PLAYER_ARROW_RIGHT_UP 玩家事件 - 释放右键

EVENT_PLAYER_ARROW_UP_DOWN 玩家事件 - 按上键

EVENT_PLAYER_ARROW_UP_UP 玩家事件 - 释放上键

EVENT_PLAYER_CHAT 玩家事件 - 聊天

EVENT_PLAYER_DEFEAT 玩家事件 - 失败

EVENT_PLAYER_END_CINEMATIC 玩家事件 - 结束电影

EVENT_PLAYER_LEAVE 玩家事件 - 离开

EVENT_PLAYER_STATE_LIMIT 玩家事件 - 状态限制

EVENT_PLAYER_VICTORY 玩家事件 - 胜利

playergameresult
常数表:

PLAYER_GAME_RESULT_DEFEAT 玩家结果 - 失败

PLAYER_GAME_RESULT_NEUTRAL 玩家结果 - 不确定

PLAYER_GAME_RESULT_TIE 玩家结果 - 平局

PLAYER_GAME_RESULT_VICTORY 玩家结果 - 胜利

playerscore
常数表:

PLAYER_SCORE_FOOD_MAXPROD 玩家积分 - 最大的人口数量

PLAYER_SCORE_FOOD_MAXUSED 玩家积分 - 最大所使用的人口数量

PLAYER_SCORE_GOLD_GIVEN 玩家积分 - 给予盟友的金子

PLAYER_SCORE_GOLD_LOST_TAX 玩家积分 - 由于税而损失的金子

PLAYER_SCORE_GOLD_LOST_UPKEEP 玩家积分 - 因为维修费而损失的金

PLAYER_SCORE_GOLD_MINED_TOTAL 玩家积分 - 所采集的金子(总共)

PLAYER_SCORE_GOLD_MINED_UPKEEP 玩家积分 - 所采集的金子(带有维修

PLAYER_SCORE_GOLD_RECEIVED 玩家积分 - 从盟友那里收到的金子

PLAYER_SCORE_HERO_TOTAL 玩家积分 - 总的英雄得分

PLAYER_SCORE_HEROES_KILLED 玩家积分 - 杀死英雄

PLAYER_SCORE_ITEMS_GAINED 玩家积分 - 获得物品

PLAYER_SCORE_LUMBER_GIVEN 玩家积分 - 给予盟友的木材

PLAYER_SCORE_LUMBER_LOST_TAX 玩家积分 - 由于税而损失的木材

PLAYER_SCORE_LUMBER_LOST_UPKEEP 玩家积分 - 由于维修费而损失的木

PLAYER_SCORE_LUMBER_RECEIVED 玩家积分 - 从盟友那里收到的木材

PLAYER_SCORE_LUMBER_TOTAL 玩家积分 - 采集到的木材

PLAYER_SCORE_MERCS_HIRED 玩家积分 - 雇佣兵

PLAYER_SCORE_RESOURCE_TOTAL 玩家积分 - 总的资源得分

PLAYER_SCORE_STRUCT_BUILT 玩家积分 - 已建造建筑

PLAYER_SCORE_STRUCT_RAZED 玩家积分 - 被毁建筑

PLAYER_SCORE_TECH_PERCENT 玩家积分 - 科技百分比

PLAYER_SCORE_TOTAL 玩家积分 - 总的整体得分

PLAYER_SCORE_UNIT_TOTAL 玩家积分 - 总的单位得分

PLAYER_SCORE_UNITS_KILLED 玩家积分 - 消灭单位

PLAYER_SCORE_UNITS_TRAINED 玩家积分 - 已训练单位
playerunitevent
常数表:



  EVENT_PLAYER_HERO_LEVEL 玩家英雄事件 - 提升一个等级

EVENT_PLAYER_HERO_REVIVABLE 玩家英雄事件 - 变得可重生的

EVENT_PLAYER_HERO_REVIVE_CANCEL 玩家英雄事件 - 取消重生

EVENT_PLAYER_HERO_REVIVE_FINISH 玩家英雄事件 - 完成重生

EVENT_PLAYER_HERO_REVIVE_START 玩家英雄事件 - 开始重生

EVENT_PLAYER_HERO_SKILL 玩家英雄事件 - 学习一项技能

EVENT_PLAYER_UNIT_ATTACKED 玩家单位事件 - 被攻击的

EVENT_PLAYER_UNIT_CHANGE_OWNER 玩家单位事件 - 变化拥有者

EVENT_PLAYER_UNIT_CONSTRUCT_CANCEL 玩家单位事件 - 取消建造

EVENT_PLAYER_UNIT_CONSTRUCT_FINISH 玩家单位事件 - 完成建造

EVENT_PLAYER_UNIT_CONSTRUCT_START 玩家单位事件 - 开始建造

EVENT_PLAYER_UNIT_DEATH 玩家单位事件 - 死亡

EVENT_PLAYER_UNIT_DECAY 玩家单位事件 - 衰退

EVENT_PLAYER_UNIT_DESELECTED 玩家单位事件 - 取消选择

EVENT_PLAYER_UNIT_DETECTED 玩家单位事件 - 被发现

EVENT_PLAYER_UNIT_DROP_ITEM 玩家单位事件 - 丢失一件物品

EVENT_PLAYER_UNIT_HIDDEN 玩家单位事件 - 隐藏

EVENT_PLAYER_UNIT_ISSUED_ORDER 玩家单位事件 - 发布一个无目标的

EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER 玩家单位事件 - 发布一个锁定一个

EVENT_PLAYER_UNIT_ISSUED_TARGET_ORDER 玩家单位事件 - 发布一个目标指令

EVENT_PLAYER_UNIT_ISSUED_UNIT_ORDER 玩家单位事件 - 发布一个锁定一个

EVENT_PLAYER_UNIT_LOADED 玩家单位事件 - 装进了传送门

EVENT_PLAYER_UNIT_PAWN_ITEM 玩家单位事件 - 抵押物品(到商店)

EVENT_PLAYER_UNIT_PICKUP_ITEM 玩家单位事件 - 获得一件物品

EVENT_PLAYER_UNIT_RESCUED 玩家单位事件 - 被营救了

EVENT_PLAYER_UNIT_RESEARCH_CANCEL 玩家单位事件 - 取消研究

EVENT_PLAYER_UNIT_RESEARCH_FINISH 玩家单位事件 - 完成研究

EVENT_PLAYER_UNIT_RESEARCH_START 玩家单位事件 - 开始研究

EVENT_PLAYER_UNIT_SELECTED 玩家单位事件 - 被选择

EVENT_PLAYER_UNIT_SELL 玩家单位事件 - 贩卖一个单位

EVENT_PLAYER_UNIT_SELL_ITEM 玩家单位事件 - 购买物品(从商店)

EVENT_PLAYER_UNIT_SPELL_CAST 玩家单位事件 - 开始施放一种技能

EVENT_PLAYER_UNIT_SPELL_CHANNEL 玩家单位事件 - 开始一种持续性技

EVENT_PLAYER_UNIT_SPELL_EFFECT 玩家单位事件 - 开始一种技能的效

EVENT_PLAYER_UNIT_SPELL_ENDCAST 玩家单位事件 - 停止施放一种技能

EVENT_PLAYER_UNIT_SPELL_FINISH 玩家单位事件 - 施放技能结束

EVENT_PLAYER_UNIT_SUMMON 玩家单位事件 - 产生一个召唤单位

EVENT_PLAYER_UNIT_TRAIN_CANCEL 玩家单位事件 - 取消训练一个单位

EVENT_PLAYER_UNIT_TRAIN_FINISH 玩家单位事件 - 完成训练一个单位

EVENT_PLAYER_UNIT_TRAIN_START 玩家单位事件 - 开始训练一个单位

EVENT_PLAYER_UNIT_UPGRADE_CANCEL 玩家单位事件 - 取消升级

EVENT_PLAYER_UNIT_UPGRADE_FINISH 玩家单位事件 - 完成升级

EVENT_PLAYER_UNIT_UPGRADE_START 玩家单位事件 - 开始升级

EVENT_PLAYER_UNIT_USE_ITEM 玩家单位事件 - 使用一件物品

race
常数表:

  RACE_DEMON 恶魔族

RACE_HUMAN 人族

RACE_NIGHTELF 暗夜精灵族

RACE_ORC 兽族

RACE_OTHER 其他族

RACE_UNDEAD 不死族

racepreference
常数表:

  RACE_PREF_DEMON

RACE_PREF_HUMAN

RACE_PREF_NIGHTELF

RACE_PREF_ORC

RACE_PREF_RANDOM

RACE_PREF_UNDEAD

RACE_PREF_USER_SELECTABLE

raritycontrol 常数表:

  RARITY_FREQUENT 频率控制 - 普通频率

RARITY_RARE 频率控制 - 罕见的

startlocprio 常数表:

  MAP_LOC_PRIO_HIGH 起始位置分布优先权 - 高

MAP_LOC_PRIO_LOW 起始位置分布优先权 - 低

MAP_LOC_PRIO_NOT 起始位置分布优先权 - 无

texmapflags
常数表:

  TEXMAP_FLAG_NONE 地图涂层标志 - 无

TEXMAP_FLAG_WRAP_U 地图涂层标志 - 重叠(U)

TEXMAP_FLAG_WRAP_UV 地图涂层标志 - 重叠(UV)

TEXMAP_FLAG_WRAP_V 地图涂层标志 - 重叠(V)
unitevent
常数表:

  EVENT_UNIT_ACQUIRED_TARGET 单位事件 - 获得一个目标

EVENT_UNIT_ATTACKED 单位事件 - 被攻击

EVENT_UNIT_CHANGE_OWNER 单位事件 - 变化拥有者

EVENT_UNIT_CONSTRUCT_CANCEL 单位事件 - 取消建造

EVENT_UNIT_CONSTRUCT_FINISH 单位事件 - 完成建造

EVENT_UNIT_DAMAGED 单位事件 - 接受伤害

EVENT_UNIT_DEATH 单位事件 - 死亡

EVENT_UNIT_DECAY 单位事件 - 衰退

EVENT_UNIT_DESELECTED 单位事件 - 取消选择

EVENT_UNIT_DETECTED 单位事件 - 被发现

EVENT_UNIT_DROP_ITEM 单位事件 - 丢失一件物品

EVENT_UNIT_HERO_LEVEL 英雄单位事件 - 提升一个等级

EVENT_UNIT_HERO_REVIVABLE 英雄单位事件 - 变得可重生的

EVENT_UNIT_HERO_REVIVE_CANCEL 英雄单位事件 - 取消重生

EVENT_UNIT_HERO_REVIVE_FINISH 英雄单位事件 - 完成重生

EVENT_UNIT_HERO_REVIVE_START 英雄单位事件 - 开始重生

EVENT_UNIT_HERO_SKILL 英雄单位事件 - 学习一项技能

EVENT_UNIT_HIDDEN 单位事件 - 隐藏

EVENT_UNIT_ISSUED_ORDER 单位事件 - 发布一个无目标的指令

EVENT_UNIT_ISSUED_POINT_ORDER 单位事件 - 发布一个锁定一个点的

EVENT_UNIT_ISSUED_TARGET_ORDER 单位事件 - 发布一个锁定目标的指

EVENT_UNIT_LOADED 单位事件 - 装进了传送门

EVENT_UNIT_PAWN_ITEM 单位事件 - 抵押物品(到商店)

EVENT_UNIT_PICKUP_ITEM 单位事件 - 获得一件物品

EVENT_UNIT_RESCUED 单位事件 - 被营救

EVENT_UNIT_RESEARCH_CANCEL 单位事件 - 取消研究

EVENT_UNIT_RESEARCH_FINISH 单位事件 - 完成研究

EVENT_UNIT_RESEARCH_START 单位事件 - 开始研究

EVENT_UNIT_SELECTED 单位事件 - 被选择

EVENT_UNIT_SELL 单位事件 - 贩卖一个单位

EVENT_UNIT_SELL_ITEM 单位事件 - 购买物品(从商店)

EVENT_UNIT_SPELL_CAST 单位事件 - 开始施放一种技能

EVENT_UNIT_SPELL_CHANNEL 单位事件 - 开始一种持续性技能

EVENT_UNIT_SPELL_EFFECT 单位事件 - 开始一种技能的效果

EVENT_UNIT_SPELL_ENDCAST 单位事件 - 停止施放一种技能

EVENT_UNIT_SPELL_FINISH 单位事件 - 施放技能结束

EVENT_UNIT_STATE_LIMIT 单位事件 - 状态限制

EVENT_UNIT_SUMMON 单位事件 - 产生一个召唤单位

EVENT_UNIT_TARGET_IN_RANGE 单位事件 - 注意范围内的一个目标

EVENT_UNIT_TRAIN_CANCEL 单位事件 - 取消训练一个单位

EVENT_UNIT_TRAIN_FINISH 单位事件 - 完成训练一个单位

EVENT_UNIT_TRAIN_START 单位事件 - 开始训练一个单位

EVENT_UNIT_UPGRADE_CANCEL 单位事件 - 取消升级

EVENT_UNIT_UPGRADE_FINISH 单位事件 - 完成升级

EVENT_UNIT_UPGRADE_START 单位事件 - 开始升级

EVENT_UNIT_USE_ITEM 单位事件 - 使用一件物品
playerslotstate
常数表:

  PLAYER_SLOT_STATE_EMPTY 空的玩家槽

PLAYER_SLOT_STATE_LEFT 玩家离开的玩家槽

PLAYER_SLOT_STATE_PLAYING 正在使用的玩家槽

playerstate
常数表:

  PLAYER_STATE_ALLIED_VICTORY 玩家状态 - 联盟胜利

PLAYER_STATE_FOOD_CAP_CEILING 玩家状态 - 食物最大容量

PLAYER_STATE_GAME_RESULT 玩家状态 - 游戏结果

PLAYER_STATE_GIVES_BOUNTY 玩家状态 - 给予奖励

PLAYER_STATE_GOLD_GATHERED 玩家状态 - 已收集金钱

PLAYER_STATE_GOLD_UPKEEP_RATE 玩家状态 - 金钱维护率

PLAYER_STATE_LUMBER_GATHERED 玩家状态 - 已收集木材

PLAYER_STATE_LUMBER_UPKEEP_RATE 玩家状态 - 木材维护率

PLAYER_STATE_NO_CREEP_SLEEP 玩家状态 - 野生生物不睡眠

PLAYER_STATE_OBSERVER 玩家状态 - 观看者

PLAYER_STATE_OBSERVER_ON_DEATH 玩家状态 - 默认为观看者

PLAYER_STATE_PLACED 玩家状态 - 放置

PLAYER_STATE_RESOURCE_FOOD_CAP 玩家状态 - 食物容量

PLAYER_STATE_RESOURCE_FOOD_USED 玩家状态 - 食物使用

PLAYER_STATE_RESOURCE_GOLD 玩家状态 - 金钱资源

PLAYER_STATE_RESOURCE_HERO_TOKENS 玩家状态 - 使用英雄

PLAYER_STATE_RESOURCE_LUMBER 玩家状态 - 木材资源

PLAYER_STATE_UNFOLLOWABLE 玩家状态 - 不可跟随
unitstate
常数表:

  UNIT_STATE_LIFE 单位状态 - 生命

UNIT_STATE_MANA 单位状态 - 法力

UNIT_STATE_MAX_LIFE 单位状态 - 最大生命

UNIT_STATE_MAX_MANA 单位状态 - 最大法力

unittype
常数表:

  UNIT_TYPE_ANCIENT 单位类型 - 古代的

UNIT_TYPE_ATTACKS_FLYING 单位类型 - 可以攻击飞行单位

UNIT_TYPE_ATTACKS_GROUND 单位类型 - 可以攻击地 单位

UNIT_TYPE_DEAD 单位类型 - 死亡单位

UNIT_TYPE_FLYING 单位类型 - 飞行单位

UNIT_TYPE_GIANT 单位类型 - 巨人

UNIT_TYPE_GROUND 单位类型 - 地面单位

UNIT_TYPE_HERO 单位类型 - 英雄

UNIT_TYPE_MECHANICAL 单位类型 - 机械的

UNIT_TYPE_MELEE_ATTACKER 单位类型 - 肉搏攻击者

UNIT_TYPE_PEON 单位类型 - 苦工

UNIT_TYPE_PLAGUED 单位类型 - 中了瘟疫的

UNIT_TYPE_RANGED_ATTACKER 单位类型 - 远程攻击者

UNIT_TYPE_SAPPER 单位类型 - 工兵

UNIT_TYPE_SNARED 单位类型 - 被诱捕的

UNIT_TYPE_STRUCTURE 单位类型 - 建筑单位

UNIT_TYPE_STUNNED 单位类型 - 被晕眩的

UNIT_TYPE_SUMMONED 单位类型 - 被召唤的

UNIT_TYPE_TOWNHALL 单位类型 - 城镇大厅类型单位

UNIT_TYPE_UNDEAD 单位类型 - 不死的

version
常数表:

  VERSION_FROZEN_THRONE 版本 - 冰封王座

VERSION_REIGN_OF_CHAOS 版本 - 混乱之治

volumegroup
常数表:

  SOUND_VOLUMEGROUP_AMBIENTSOUNDS 场景配音

SOUND_VOLUMEGROUP_COMBAT 战斗声音

SOUND_VOLUMEGROUP_FIRE 火焰声音

SOUND_VOLUMEGROUP_MUSIC 音乐

SOUND_VOLUMEGROUP_SPELLS 动画和法术声音

SOUND_VOLUMEGROUP_UI 用户界面声音

SOUND_VOLUMEGROUP_UNITMOVEMENT 单位移动声音

SOUND_VOLUMEGROUP_UNITSOUNDS 单位回应声音