nspe: {code: "", name: "支柱" , tip: "", type: Type.Unit.Orc.Campaign.Unit},
oose: {code: "", name: "科多兽(怀需要分配驾驭者" , tip: "", type: }," , tip: "", type: Type.Unit.Orc.Campaign.Unit},
owar: {code: "", name: "兽族战争首领" , tip: "", type: Type.Unit.Orc.Campaign.Unit},
ogrk: {code: "", name: "加嗦克" , tip: "", type: Type.Unit.Orc.Campaign.Unit},
oswy: {code: "", name: "灵魂飞龙" , tip: "", type: Type.Unit.Orc.Campaign.Unit},
ownr: {code: "", name: "双足飞龙(不需要分驾驭者" , tip: "", type:  Type.Unit.Orc.Campaign.Unit},
odkt: {code: "", name: "德拉克苏尔" , tip: "", type: Type.Unit.Orc.Campaign.Unit},
obot: {code: "", name: "兽族运输船" , tip: "", type: Type.Unit.Orc.Campaign.Unit},
odes: {code: "", name: "兽族护卫舰" , tip: "", type: Type.Unit.Orc.Campaign.Unit},
ojgn: {code: "", name: "兽族魔力战舰" , tip: "", type: Type.Unit.Orc.Campaign.Unit},
nw2w: {code: "", name: "兽族巫师" , tip: "", type: Type.Unit.Orc.Campaign.Unit},
nchw: {code: "", name: "邪恶的巫师" , tip: "", type: Type.Unit.Orc.Campaign.Unit},
nchg: {code: "", name: "邪恶的兽族步兵" , tip: "", type: Type.Unit.Orc.Campaign.Unit},
nchr: {code: "", name: "邪恶的掠夺者" , tip: "", type: Type.Unit.Orc.Campaign.Unit},
nckb: {code: "", name: "邪恶的科多兽" , tip: "", type: Type.Unit.Orc.Campaign.Unit},
ncpn: {code: "", name: "邪恶的苦工" , tip: "", type: Type.Unit.Orc.Campaign.Unit},

npgr(能里产生器" , tip: "", type: Type.Unit.Orc.Campaign.Building},
oshy: {code: "", name: "兽族船坞" , tip: "", type: },
nwc1: {code: "", name: "双足飞龙牢笼(1" , tip: "", type: Type.Unit.Orc.Campaign.Building},
nwc2: {code: "", name: "双足飞龙牢笼(2" , tip: "", type: Type.Unit.Orc.Campaign.Building},
npgf: {code: "", name: "猪圈农场" , tip: "", type: Type.Unit.Orc.Campaign.Building},
ndrb: {code: "", name: "龙之栖木" , tip: "", type: Type.Unit.Orc.Campaign.Building},
nbfl: {code: "", name: "血浴之泉" , tip: "", type: Type.Unit.Orc.Campaign.Building},
ndfl: {code: "", name: "被污染的生命之泉" , tip: "", type: Type.Unit.Orc.Campaign.Building},
ocbw: {code: "", name: "邪恶兽族地洞(混乱的" , tip: "", type: Type.Unit.Orc.Campaign.Building},

Nsjs: {code: "", name: "陈-风暴烈酒" , tip: "", type: Type.Unit.Orc.Campaign.Hero},
0drt: {code: "", name: "德雷克萨尔" , tip: "", type: Type.Unit.Orc.Campaign.Hero},
0grh: {code: "", name: "格罗姆地狱咆哮" , tip: "", type: Type.Unit.Orc.Campaign.Hero},
Opgh: {code: "", name: "格罗姆一地狱咆哮(恶魔附体", , tip: "", type: Type.Unit.Orc.Campaign.Hero},
0gld: {code: "", name: "古尔丹" , tip: "", type: Type.Unit.Orc.Campaign.Hero},
0cbh: {code: "", name: "卡林-血蹄" , tip: "", type: Type.Unit.Orc.Campaign.Hero},
0cb2: {code: "", name: "卡林血蹄(资料片" , tip: "", type: Type.Unit.Orc.Campaign.Hero},
Orex: {code: "", name: "雷克萨" , tip: "", type: Type.Unit.Orc.Campaign.Hero},
Orkn: {code: "", name: "洛克汗" , tip: "", type: Type.Unit.Orc.Campaign.Hero},
0thr: {code: "", name: "萨尔" , tip: "", type: Type.Unit.Orc.Campaign.Hero},
0sam: {code: "", name: "萨穆罗" , tip: "", type: Type.Unit.Orc.Campaign.Hero},
Nbbc: {code: "", name: "黑岩氏族的剑圣" , tip: "", type: Type.Unit.Orc.Campaign.Hero},

omtg: {code: "", name: "马索格" , tip: "", type: Type.Unit.Orc.Campaign.Special},
ovlj: {code: "", name: "沃尔京" , tip: "", type: Type.Unit.Orc.Campaign.Special},
onzg: {code: "", name: "那滋盖尔" , tip: "", type: Type.Unit.Orc.Campaign.Special}, 
negz: {code: "", name: "工程师加磁劳" , tip: "", type: Type.Unit.Orc.Campaign.Special},
nmsh: {code: "", name: "米纱" , tip: "", type: Type.Unit.Orc.Campaign.Special},
Otcc: {code: "", name: "卡林-血蹄(过场动画" , tip: "", type: Type.Unit.Orc.Campaign.Special},
ngbl: {code: "", name: "地精爆破T" , tip: "", type: Type.Unit.Orc.Campaign.Special},